name: BuildPulse

on:
  push:

defaults:
  run:
    shell: bash

permissions:
  actions: read

jobs:
  buildpulse:
    name: Upload JUnit XML report to BuildPulse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          run-id: 9915956041
          github-token: ${{ github.token }}
      - run: ls -la
